import type { AppProps } from 'next/app'
import { appWithTranslation } from 'next-i18next'
import { Roboto } from '@next/font/google'
import '@/styles/globals.scss'
import '@/styles/reset.scss'
import Layout from '@/src/components/Layout'
import Locale from '@/src/components/Locale'
import Head from 'next/head'
import { AnimatePresence } from 'framer-motion'
import uuid from 'react-uuid'

const roboto = Roboto({
    subsets: ['latin', 'cyrillic', 'cyrillic-ext'],
    weight: ['100', '300', '400', '500', '700', '900'],
})

function App({ Component, pageProps }: AppProps) {
    return (
        <>
            <Head>
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <meta name='description' content='Generated by create next app' />
                {/*<link rel='icon' href='/favicon.ico' />*/}
            </Head>
            <AnimatePresence>
                <div className={roboto.className} key={uuid()}>
                    <Locale />
                    <Layout>
                        <Component {...pageProps} />
                    </Layout>
                </div>
            </AnimatePresence>
        </>
    )
}

export default appWithTranslation(App)
